### ISSUE TITLE
Error: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.

### ISSUE THREAD

**Issue by thomasmerz** [inokawa/lang-box#10]
Since Feb, 22nd 2022 I'm getting these error messages and don't have a clue WHY? Can you please help and advice? Thank you 😃 

https://github.com/thomasmerz/lang-box/runs/5297119790?check_suite_focus=true
```
Error: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
    at ApiClient.fetch (file:///home/runner/work/lang-box/lang-box/src/api.js:20:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async file:///home/runner/work/lang-box/lang-box/src/index.js:114:18
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lang-box@1.0.0 start: `node --experimental-modules --es-module-specifier-resolution=node src/index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lang-box@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-02-23T00_55_44_139Z-debug.log
Error: Process completed with exit code 1.
```

**Comment by inokawa** [comment]
It seems like you called GitHub API too many times (because this action uses GitHub API).

https://docs.github.com/en/rest/overview/resources-in-the-rest-api#secondary-rate-limits

**Comment by thomasmerz** [comment]
@inokawa 

Strange, my **[billing](https://github.com/settings/billing)** doesn't show this:

<img width="445" alt="grafik" src="https://user-images.githubusercontent.com/18568381/155308212-4df479f0-470b-4c9a-8fd6-6e590dc3d727.png">


I also checked my **[rate-limit status](https://docs.github.com/en/rest/reference/rate-limit)**:
```
$ curl   -H "Accept: application/lang-box@1.0.0+json"   https://api.github.com/rate_limit 2>/dev/null | jq
{
  "resources": {
    "core": {
      "limit": 60,
      "remaining": 60,
      "reset": 1645618513,
      "used": 0,
      "resource": "core"
    },
    "graphql": {
      "limit": 0,
      "remaining": 0,
      "reset": 1645618513,
      "used": 0,
      "resource": "graphql"
    },
    "integration_manifest": {
      "limit": 5000,
      "remaining": 5000,
      "reset": 1645618513,
      "used": 0,
      "resource": "integration_manifest"
    },
    "search": {
      "limit": 10,
      "remaining": 10,
      "reset": 1645614973,
      "used": 0,
      "resource": "search"
    }
  },
  "rate": {
    "limit": 60,
    "remaining": 60,
    "reset": 1645618513,
    "used": 0,
    "resource": "core"
  }
}
```
This looks also "good" 🤷🏻‍♂️ Do you have an idea **what** exactly is being limited here and why?
